### ISSUE TITLE
[FEATURE REQUEST] - Filename and path instead of prefix

### ISSUE THREAD

**Issue by Erehr** [receyuki/comfyui-prompt-reader-node#1]
Basically what multiple other image saver nodes have and a must-have for organization. 

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/13292573/23c1651f-ae15-4791-b867-d76d2cfb0122)

**Comment by receyuki** [comment]
I just added this feature to the dev branch, and it looks like this.
<img width="380" alt="截屏2023-10-09 上午4 43 18" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/6db98679-11c7-4f5d-b1b4-9372278cd9dc">
Currently, it support the following placeholders. Can you think of any others I can add?
```python
"%date": date_format,
"%time": time_format,
"%counter": counter,
"%seed": seed,
"%steps": steps,
"%cfg": cfg,
"%extension": extension,
"%model": model_name,
"%sampler": sampler_name,
"%scheduler": scheduler,
"%quality": jpg_webp_quality,
```

**Comment by Erehr** [comment]
Recently found [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) "Ability to "send" an image to a Load Image node in either the current or a different workflow" and thought it would work great with this extension for various actions like upscale where I don't have to manually fill all settings back.

Unfortunately I found that Prompt Reader node can't work as a bridge of sorts to read that data from another image node with the setting is converted to input. Also sampler and scheduler output is missing in reader but it's there in saver.
![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/13292573/cda4816d-8c40-4d8d-b2e4-d250d2296af8)

**Comment by receyuki** [comment]
`LoadImage` only outputs the image itself and doesn't include any metadata. Connecting `LoadImage` with `PromptReader` doesn't make sense.

About `sampler_name` and `scheduler`, different tools support different samplers and schedulers. Even the same sampler may have different names on different tools. Considering compatibility issues, using the `sampler_name` and `scheduler` from the metadata directly isn't a good choice. Therefore, I would recommend using the `ParameterGenerator` to generate `sampler_name` and `scheduler`.

**Comment by receyuki** [comment]
Please update to the latest version to try out the new feature you requested.
