### ISSUE TITLE
[FEATURE REQUEST] - Batch support on ComfyUI

### ISSUE THREAD

**Issue by Tirshea** [receyuki/comfyui-prompt-reader-node#13]
### Summary

First, thank you for the node suite. I've been playing with it the last few days and it screams "must-have batch tool for upscaling workflow from low-quality rushes/seed images".

The abilty to load images with their metadata is awesome, especially when - like me - you use wildcards a lot.

But when we design an upscaling workflow, we most likely want it to support batch loading.

I tried the obvious way with "convert image to input" on the reader but I couldn't find any node able to link to this "image" input.

![image](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/19656257/85090046-cca7-462a-8d50-288bc45b91eb)

### Basic Example

Abillity to connect image loaders to SD_Prompt_Read node.

**Comment by PSVinrael** [comment]
Just a +1 to say this node is exactly what I've been looking for to finish an A1111 based 1.5 to SDXL Upscale Workflow and literally the only thing missing is batch processing, would be perfect in that case.

**Comment by receyuki** [comment]
@Tirshea @PSVinrael 
The batch processing feature is now ready! Please update to the latest version. 

Simply connect the `Batch Loader` to the `Prompt Reader`. When you set the `image_load_limit` to 1, you’ll be able to use the `Batch Loader` just like the `LoadImageInFolder` you mentioned above.
