### ISSUE TITLE
[BUG] - %counter overwriting

### ISSUE THREAD

**Issue by Tirshea** [receyuki/comfyui-prompt-reader-node#14]
### Description

ComfyUI: When using %counter in the filename, it will overwrite existing images. Basically %counter will reset to 0 everytime you queue up a render.

Result : When you queue **_X_** iterations with Batch_Size = **_Y_**, you will have **_Y_** images at the end, with %counter values from 0 to **_Y_**

Suggestion : have it work like the basic SaveImage node, where you supply the path&filename, and the counter is automatically added and incremented based on existing images with that filename at target path.

### Version

1.3.4

### OS

Windows

### Tool

A1111's webUI

**Comment by receyuki** [comment]
Fixed in v1.0.1, please update the node to the latest version.

**Comment by Tirshea** [comment]
Fix confirm, thanks for your effort !
