### ISSUE TITLE
[FEATURE REQUEST] - VAE selector for SD Parameter Generator

### ISSUE THREAD

**Issue by alessandroperilli** [receyuki/comfyui-prompt-reader-node#15]
### Summary

Right now the` SD Parameter Generator` node exports a VAE. Great, but it doesn't allow to define which one. Usually, this is a task for the Checkpoint Loader, as in the following case, with the `Efficient Loader` node:

<img width="370" alt="Screenshot 2023-10-31 at 10 32 25" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/d3720cf3-c76c-46a2-a423-fcb19d123312">

but, given that the use already has to define the type of model (SD1, SD2, SDXL), it would be convenient to have the VAE selector (mainly useful for SD1.5) baked into the Parameter Generator.

### Basic Example

Just like the dropdown in my screenshot above.

**Comment by receyuki** [comment]
I have read the source code of Efficient Loader. I should be deploying this feature (along with a few other new features) in version 1.1.0, while version 1.0.1 will primarily fix existing bugs.

**Comment by alessandroperilli** [comment]
The new version of the node is fantastic. Thank you.
