### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by liaosu0755** [receyuki/comfyui-prompt-reader-node#2]
File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node\nodes.py", line 27, in <module>
    from .stable_diffusion_prompt_reader.sd_prompt_reader.constants import (
ModuleNotFoundError: No module named 'comfyui-prompt-reader-node.stable_diffusion_prompt_reader.sd_prompt_reader'

Cannot import L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node module for custom nodes: No module named 'comfyui-prompt-reader-node.stable_diffusion_prompt_reader.sd_prompt_reader'
Traceback (most recent call last):

**Comment by receyuki** [comment]
This issue is caused by incorrect installation of the submodule. Please follow the instructions below to reinstall it. 
https://github.com/receyuki/comfyui-prompt-reader-node#installation

**Comment by liaosu0755** [comment]
> 此问题是由子模块安装不正确引起的。请按照以下说明重新安装它。 https://github.com/receyuki/comfyui-prompt-reader-node#installation该问题是由于子模块安装不正确造成的。请按照以下说明重新安装。

Thanks, problem solved, I guess I didn't use "--recursive" before clone.

**Comment by receyuki** [comment]
对.但如果你用git手动装的话记得更新的时候也要按照说明上的更新.不然子模块也更不上.
所以推荐用ComfyUI Manager.那个会自动处理子模块
