### ISSUE TITLE
[FEATURE REQUEST] - output model/checkpoint name as string

### ISSUE THREAD

**Issue by someghuser** [receyuki/comfyui-prompt-reader-node#23]
### Summary

Node output of model/checkpoint name as string

### Basic Example

When trying to generate similar images, different checkpoint could have been used, it automates the selection of checkpoint.

**Comment by receyuki** [comment]
But in reality, no KSampler can input a checkpoint name in STRING format. 

Since the name of a checkpoint is not unique (as you can rename it anytime), I think linking the checkpoint name output to the KSampler is highly likely to cause issues.

**Comment by someghuser** [comment]
I use this right now CheckpointSelector  > CheckpointLoaderSimple > KSampler

How about sdpromptreader.ckpt_name > CheckpointLoaderSimple > KSampler

Is this possible? Even in the same system? 

You will not implement because it might break for most people? Doesn't comfy tell you when a controlnet model is missing so you can download it? It's the same principle here, isn't it?

I hope it's feasible.

**Comment by receyuki** [comment]
I guess you are right. I will add the MODEL_NAME. 

BTW, instead of using CheckpointLoader, you might want to try out my `Parameter Generator`.

**Comment by receyuki** [comment]
Please try the new version.

**Comment by someghuser** [comment]
It works. It shows a python error if the checkpoint doesn't exist.

Thank you

**Comment by ghostsquad** [comment]
Here's what I'm doing so I can use other nodes with more features as opposed to being stuck with the parameter generator:

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/903488/bd6df2ec-5d4a-4108-bef7-618c768085b7)
