### ISSUE TITLE
[BUG] - Prompt Merger producing unsanitised output with concatenated NULL strings.

### ISSUE THREAD

**Issue by RangerFrank** [receyuki/comfyui-prompt-reader-node#29]
### Description

SDPromptMerger throws an error when fed empty strings

Error occurred when executing SDPromptMerger:

list index out of range

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 143, in recursive_execute
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs, prompt, extra_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 27, in get_input_data
    obj = outputs[input_unique_id][output_index]
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

### Reproduction steps

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/14126780/14cc6841-de18-4e97-9036-f9724023eae1)


### Image file

_No response_

**Comment by receyuki** [comment]
Would you mind sending me this part of the workflow? I can't reproduce this issue with my custom nodes.
