### ISSUE TITLE
[FEATURE REQUEST] - File name/Path

### ISSUE THREAD

**Issue by drago87** [receyuki/comfyui-prompt-reader-node#3]
### Summary

Having a file name output on the file reader would be nice and path to the file would be nice

### Basic Example

Having the file name and path lets you easy place the new image in the same folder and make a text file with comments or information named the same as the new image for easy sorting

**Comment by receyuki** [comment]
I'm sorry, but I don't quite understand your meaning. Are you talking about the Prompt Reader Node or the Prompt Saver Node? If you're talking about #1, that feature has already been added to the dev branch.

**Comment by drago87** [comment]
It was the first one a passteue for the saver would be nice to

**Comment by receyuki** [comment]
Outputting the file name is possible, but outputting the file path is not possible. The Prompt Reader Node uses the same file upload method as the built-in Load Image node. It first uploads the image to the input folder on the server before reading it. So, the Prompt Reader Node would only be able to get the location of the input folder.

**Comment by drago87** [comment]
That would probebly be enuff

**Comment by receyuki** [comment]
Please update to the latest version to try out the new feature you requested.
