### ISSUE TITLE
[BUG] - SD Prompt Saver multiplying by batch number

### ISSUE THREAD

**Issue by RangerFrank** [receyuki/comfyui-prompt-reader-node#30]
### Description

Single images work fine, increasing batch size results in multiplying results,  2x2, 3x3, etc. So a with a batch size set to 4 you get 16 images being processed in SD Prompt Saver, there's also a problem with filename output sanitation, error related: 

Error occurred when executing StringFunction|pysssss:

'list' object has no attribute 'replace'

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\string_function.py", line 43, in exec
    out = text_a.replace(text_b, text_c)
          ^^^^^^^^^^^^^^

Similar issue seems to occur with SD Prompt Merge when using null strings that I already posted about.

### Reproduction steps

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/14126780/750cd523-d3e2-49b4-b296-8a5d7f9dd7cb)

### Image file

Workflow image:
![ComfyUI_34305983516218_2023-12-04_51](https://github.com/receyuki/comfyui-prompt-reader-node/assets/14126780/79a8c178-425c-4430-8242-007ddaba5b9d)

**Comment by RangerFrank** [comment]
Yes, the intention is to create keyword files at image generation for a number of purposes including being able to reference, parse, and process those keywords back into the same or different workflows for an iterative generation, having training files pre-made at the generation stage also provides flexibility and removes a step for training loras by including it in image gen.

Also I can't get pythongosssss savetext to work and I think it might be to do with the same issue with being passed a list not a string. Do you know if there's a simple way to string split the WD14 output in the meantime?

**Comment by receyuki** [comment]
<img width="437" alt="image" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/73b20762-089f-4274-9860-5db71413752c">  

The [comfyroll](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes) includes a node called “CR Split String” which can be used to split a string.

**Comment by receyuki** [comment]
Please try out the `save_metadata_file` feature in the new version of `Prompt Saver` node.

**Comment by RangerFrank** [comment]
This works well for my purposes, appreciated.
