### ISSUE TITLE
[BUG] - title

### ISSUE THREAD

**Issue by siliconecomputervision** [receyuki/comfyui-prompt-reader-node#33]
### Description

Error occurred when executing SDPromptReader:

invalid literal for int() with base 10: 'None'

File "C:\Users\rober\Downloads\AI Creations\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\rober\Downloads\AI Creations\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\rober\Downloads\AI Creations\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\rober\Downloads\AI Creations\ComfyUI\custom_nodes\comfyui-prompt-reader-node\nodes.py", line 161, in load_image
seed = int(
^^^^

I use impact wildcard nodes for my prompt strings/wildcards. Can I assume this is incompatible with the prompt reader?
This workflow was attempting to load an image that I have genned with verifiable metadata using the batch loader connected to the prompt reader.

**Comment by siliconecomputervision** [comment]
looks like this was due to the complexity of my workflow. Removing all impactwildcard nodes and just using a SINGLE clip text encode for positive and a single for negative, I was able to get the SDPromptreader to work successfully. So i'm thankful it works, but it seems like this is severely limiting.

**Comment by receyuki** [comment]
Instead of using the `Prompt Reader` node to extract metadata from your complex workflow, you can use a `Prompt Saver` node to save images. This ensures metadata reading is not affected by the complexity of your workflow, and it also allows you to generate images that are compatible with other metadata reading tools.
