### ISSUE TITLE
[FEATURE REQUEST] - Save LoRA information in civitAI compatible format from the CivitAI nodes.

### ISSUE THREAD

**Issue by RangerFrank** [receyuki/comfyui-prompt-reader-node#35]
### Summary

Save Checkpoint and LoRA information in civitAI compatible format from the CivitAI nodes.

This is just about the only feature I feel like I'm missing now, at the moment I'm forced to use cute-comfy to save full civitAI compatible metadata including all checkpoints and loras used. However cute-comfy has it's own limitations because it's not a node but listener so it has no ability to tell it exactly which metadata to record if using unsupported nodes.

### Basic Example

The civitAI nodes can be populated with AIR codes that are civitAI compatible for linking resources.

**Comment by receyuki** [comment]
Could you provide some examples for reference? I’m not sure how civitai recognises lora and ckpt.

**Comment by RangerFrank** [comment]
https://github.com/zer0TF/cute-comfy

**Comment by receyuki** [comment]
Alright, now I understand. Cute-comfy will write the hash value of Lora, just like the existing calculate_model_hash. The current nodes cannot read the filename or hash of Lora, so if I need to implement this feature, I will have to write a new Lora loader node.

**Comment by RangerFrank** [comment]
https://github.com/civitai/civitai_comfy_nodes

**Comment by receyuki** [comment]
Please try the latest version.

**Comment by RangerFrank** [comment]
> Please try the latest version.

Great job, works like a charm.
