### ISSUE TITLE
[BUG] - Exception after updating ComfyUI

### ISSUE THREAD

**Issue by mwo72** [receyuki/comfyui-prompt-reader-node#37]
### Description

There is an exception message "'NoneType' object has no attribute 'endswith'" after updating ComfyUI

### Reproduction steps

1. Go into the ComfyUI Manager Menu
2. Click 'Update All'
3. Wait and restart 
4. Create a simple workflow with 'SD Batch Loader' and 'SD Prompt Reader'
5. Press 'Queue Prompt'

### Image file

![Exception](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/38641235-e893-4d27-a68e-516fac8d136e)

**Comment by receyuki** [comment]
Can you post the original image (ComfyUI_144103.jpg) here?

**Comment by mwo72** [comment]
![ComfyUI_144103](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/3a612ebf-e7d2-46c1-bcc4-58637ed0ee53)

**Comment by receyuki** [comment]
That's strange, everything is working fine on my end. Have you tried reloading the browser tab? What is the error message displayed on your server terminal?

**Comment by mwo72** [comment]
I have made several tests, including rebooting. At first I thought it was an incompatibility with another package, so I have completely reinstall from scratch ComfyUI. It turned out the problem occurs after the update.

![Console](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/0d411ab8-1868-4a53-9523-35167be8462f)

**Comment by receyuki** [comment]
I've finally found the bug, and I should be able to fix it within a few hours.

**Comment by receyuki** [comment]
Done!

**Comment by mwo72** [comment]
Thank you for the fix, but something else might have been broken in the process. The preview image in the 'SD prompt reader' is no longer updated.

![PreviewNotUpdated](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/bf947427-cf22-4390-b0b1-a8a83c00c330)

**Comment by receyuki** [comment]
This is not a bug. The preview image won't work when you use the batch loader. Currently, I haven't found a good solution, so I suggest using a preview image node as an alternative.

**Comment by mwo72** [comment]
Another issue, the 'single file' mode seems to be broken

![SingleFileMode](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/af69183d-ddcb-435f-819b-04d935378c59)

**Comment by receyuki** [comment]
I've made some attempts, but the only scenario this error message is triggered is when the image does not exist. So, could you do more testing and let me know the results?

**Comment by mwo72** [comment]
Thank you for your time and sorry for all the troubles.

I am using your package with a more complex workflow than the examples that I have posted here.

After seeing your last message, I was unable to reproduce the problem with the previous example ???, but it seems to occur when the 'path' is provided by another node (WAS Suite: Text Multiline)

![SingleFileMode2](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/4b7e8c1a-788c-43d1-a326-d13289e08c6d)

After some digging, I was able to bypass this problem with the following hack (I am not a expert of Python/ComfyUI)

![fix](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/5e3d9f20-e2b4-43df-83c3-733f75f6f89c)

**Comment by receyuki** [comment]
The primitive node can work, but anyway, I will fix this.
<img width="732" alt="截屏2024-01-05 下午10 05 19" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/28d8c137-7a3b-4d9a-aa38-5a52d7deddf3">

**Comment by receyuki** [comment]
Please try the latest version.

**Comment by mwo72** [comment]
Hello, thank you for your work.

The good news, the SD batch loader is working.

The not so good news, loading a old workflow seems to be broken, but if we edit it (delete, recreate node and link), then it works again. I have no idea how ComfyUI is supposed to work with updated nodes having new inputs/outputs.

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/46244282/697a27be-6aa4-4f07-8ab3-de4df799a0a0)

Old workflow: 
[workflow.json](https://github.com/receyuki/comfyui-prompt-reader-node/files/14014067/workflow.json)

**Comment by receyuki** [comment]
Same here. TinyterraNodes provides a function to reload nodes, but sometimes this feature doesn't work, and I still have to delete and recreate nodes. So, I also wish there was a better way.

https://github.com/TinyTerra/ComfyUI_tinyterraNodes

**Comment by receyuki** [comment]
BTW, 768x768 is the optimal resolution for SDv2 so you can set the model version to SDv2 and choose 1:1.
