### ISSUE TITLE
[BUG] - SD Batch Loader and SD Prompt Reader don't work together

### ISSUE THREAD

**Issue by karl-von-knecht** [receyuki/comfyui-prompt-reader-node#38]
### Description

(Not sure if this is a bug or just me doing it wrong)
I have created a bunch of images with SD Prompt Saver. Each one has a different prompt. Now I would like to further process them in a batch using the prompt retrieved by SD Prompt Reader. But it seems I can only load the images individually and manually. Connecting the SD Batch Loader and SD Prompt Reader gives a runtime error.
Having the ability to use the original prompt in batch processing would be tremendously useful for the community, it would be really great if you have an answer to this!
![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/123109169/6541c508-a3dd-4b62-b44f-5ee42d1759c8)

**Comment by russ22cox** [comment]
I'm having a similar issue - it looks like the "image" input has been disabled on the prompt reader.  I'm guessing it was disabled until a fix is found for this issue?

**Comment by receyuki** [comment]
@russ22cox The fix is ready, and I will be releasing it in the next few days.

**Comment by receyuki** [comment]
Please try the latest version.

**Comment by russ22cox** [comment]
I deleted the node and reinstalled it from the manager.  The image input into the SD prompt reader is still not available to connect things to, can only select image manually.

**Comment by receyuki** [comment]
This is weird, have you tried deleting and recreating the node?

**Comment by russ22cox** [comment]
I installed a new version of the portable standalone build for ComfyUI, installed the manager, restarted, went to custom nodes, installed node 208 ([comfyui-prompt-reader-node](https://github.com/receyuki/comfyui-prompt-reader-node), restarted again, then spawned a SD prompt reader node.  The reader does not have an input.   The nodes.js does seem to define inputs for "class SDPromptReader", but they are not showing up. 


![missinginput](https://github.com/receyuki/comfyui-prompt-reader-node/assets/129803744/d983ba97-bec7-4605-999c-690d6b98ff0c)

**Comment by receyuki** [comment]
@russ22cox 
Right-click on the node, select "Convert image to input".
<img width="388" alt="截屏2024-02-06 下午8 05 45" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/f3d7b8ad-037c-43d5-94ba-e1542377c957">

**Comment by russ22cox** [comment]
Wow!  Thank you!  I didn't know you could turn on and off input types.  There a a bunch of other nodes that have new functionality as well because I know this.

**Comment by receyuki** [comment]
@russ22cox No worries. Perhaps watching some YouTube tutorials would be helpful for you.

**Comment by receyuki** [comment]
@karl-von-knecht I will mark this issue as closed. If the bug is not resolved after updating to the latest version, feel free to reopen it.
