### ISSUE TITLE
[BUG] - SDParameterGenerator doesn't load the seed value from previously generated images

### ISSUE THREAD

**Issue by alessandroperilli** [receyuki/comfyui-prompt-reader-node#44]
### Description

If I generate an image with a workflow that includes the `SDParameterGenerator` node (like the AP Workflow or the default ComfyUI workflow in the image below), and I later drag that image into the ComfyUI canvas, or Load it via the floating menu, all generation parameters are correctly loaded except the seed value. That remains to -1. 

### Reproduction steps

1. Load the default ComfyUI workflow. 
2. Convert any control in the KSampler from widget to input
3. Link the KSampler input to the corresponding output in the `SDParameterGenerator` node
4. Generate a couple of images 
5. Load the before last image and notice that the seed remains at -1

### Image file

<img width="1159" alt="Screenshot 2024-01-13 at 10 04 46" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/30f9c5c5-5941-483c-be74-0f223d716c19">

**Comment by receyuki** [comment]
This is not a bug. Since I borrowed the entire seed generator from rgthree, my understanding is that it works by storing the seed in a location that is not part of the workflow. Therefore, to implement this feature technically, I would need to rewrite rgthree’s seed generator (something I don’t believe is worthwhile doing). 
Alternatively, you could ask rgthree if he would be interested in modifying it to suit your preferences, and then I could learn from his updated code lol.

**Comment by alessandroperilli** [comment]
I'd be happy to do that, but are we sure? I perfectly remembered that dragging a previously-generated image into the ComfyUI canvas would load the seed number inside the `SDParametersGenerator` node without issues. 
And I have one AP Workflow user who tells me it used to work fine with AP Workflow 6.0 and now it's not working with 7.0. 

Given that I changed absolutely nothing in the workflow about the seed in the transition from 6 to 7, and given the behaviour I just described above, I thought something changed in the node itself.

I have no idea how this feature is implemented. Is it possible that @rgthree changed something in his custom node suite and that impacted the behavior of your `SDParametersGenerator` node? (Sorry if it's a stupid question)

**Comment by alessandroperilli** [comment]
It's working now... I just tried again and the seed loads without issues, as usual. I have no idea what's happening :)

**Comment by alessandroperilli** [comment]
I'm closing this for the time being.

**Comment by receyuki** [comment]
You're right, I will go over rgthree's code again carefully. His code works perfectly, the problem should be with my modifications.

**Comment by alessandroperilli** [comment]
Thank you for fixing this!
