### ISSUE TITLE
[FEATURE REQUEST] - Counter in PATH

### ISSUE THREAD

**Issue by Latentnaut** [receyuki/comfyui-prompt-reader-node#49]
> **filename & path**
> %counter cannot be used for path, it can only be used for filename. This %counter is slightly different from the %counter in the built-in Saver node, it will count all image files in the path.

I know it's hardly imposible to please everyone. But I would like to have a counter in the path, like `%date/%counter/`, so that I can keep my renders separately, it's much easier for my workflow. Is there any workaround to achive this (not manually)?

**Comment by receyuki** [comment]
This is why I like ComfyUI.
<img width="844" alt="截屏2024-02-06 下午9 40 33" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/c834560f-e3e9-4fdf-ab41-e620fd994957">

primitive node → Integer to String (Comfyroll) → Text Concatenate (WAS Node Suite)
Any similar nodes would also work.

**Comment by Latentnaut** [comment]
Oh yes, you made my day :)

I need to sharp my basic programming skills as it was a easy task. Thank you for your patience and support.

If I would have the skills, I would set a variable call %sequencer to count my folders, and reset to 1 every new day detected.

Again, thank you for your help.
