### ISSUE TITLE
[BUG] - SD Prompt Saver does not work with batches

### ISSUE THREAD

**Issue by hrkrx** [receyuki/comfyui-prompt-reader-node#5]
### Description

When generating more than one image in ComfyUI, the SD Prompt Saver only saves the last image.

It shows the correct number of images, but each image is the same last image (if batch = 4, you'll see 4 times the last image in the preview)

### Reproduction steps

1. set Batch > 1
2. Generate Images
3. look at preview in SD Promt Saver Node
4. look at files saved

### Image file

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/5176531/b8288a05-dc13-4ed2-a3a6-bc54971bc504)

### Version

1.0.0

**Comment by receyuki** [comment]
I can't believe I didn't notice this bug. Thx.

**Comment by receyuki** [comment]
Fixed in v1.0.0

**Comment by hrkrx** [comment]
Happens to the best ;)

Thanks for the quick fix!
