### ISSUE TITLE
[BUG] - More precise REFINER_START

### ISSUE THREAD

**Issue by Latentnaut** [receyuki/comfyui-prompt-reader-node#52]
### Summary

In SD Parameter Generator, the **refiner_start** parameter always rounds to the tens.

### Basic Example

0.3 = 30%
0.2 = 20%
**0.25 = 30%**

If a want to generate with 100 total steps, and start the refiner at 25, right now it's not possible (it rounds to 30).

**Comment by receyuki** [comment]
This is weird, everything is working fine on my end, maybe I misunderstood your issue?
<img width="651" alt="截屏2024-02-06 下午9 50 06" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/c6a23a49-ef2d-4d73-a916-09ca66d9e2a3">

**Comment by Latentnaut** [comment]
Hummm, you are right, it's very strange because I've checked just now and it works as expected.

Thank you for your support.

**Comment by receyuki** [comment]
If the issue occurs again, feel free to reopen it at any time.
