### ISSUE TITLE
[FEATURE REQUEST] - Generic string placeholder input for prompt saver 

### ISSUE THREAD

**Issue by vidyava** [receyuki/comfyui-prompt-reader-node#53]
### Summary

Hello,
I'm loving this node set, and one thing I'd like to have is the ability to pass in a string to the prompt saver node that would get filled in as a placeholder. This way I could craft custom strings that I wanted to be part of a filename. Currently I've just modified `scheduler_str` back into existence and use `%scheduler` to do this, but it would be nice to not redo this any time I update. 

I don't know whether the node should handle filename sanitation or leave that up to the user, though.

### Basic Example

Example: I want to make a series of images with a specific theme that gets passed into the prompt, e.g. "cyberpunk". I would pass this string into the prompt saver node as an input, say "custom", then set an output filename of `%date_%custom_%counter` to get `2024-02-02_cyberpunk_00001.png`

**Comment by receyuki** [comment]
Interesting idea. But in fact, you can absolutely achieve the effect you mentioned by combining multiple nodes.

<img width="674" alt="截屏2024-02-08 下午9 11 22" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/5635602e-dd45-465a-949b-de08d4443076">

Primitive node → Text Concatenate (WAS Node Suite) → filename
This is why we love ComfyUI, isn't it?

**Comment by vidyava** [comment]
For some reason I didn't think you'd be able to pass in placeholders as text and have them still replaced, no idea why. Thanks for the solution!
