### ISSUE TITLE
[BUG] - When attempting to read the prompt of a .png file in Comfyui that does not have any prompt data an error is produced

### ISSUE THREAD

**Issue by MokkaBoss1** [receyuki/comfyui-prompt-reader-node#58]
### Description

the following error is produced when the above the condition is met.

Error occurred when executing SDPromptReader:

No data detected or unsupported format

File "F:\comfynew\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\comfynew\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\comfynew\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\comfynew\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node\nodes.py", line 159, in load_image
raise ValueError(MESSAGE["format_error"][1])

### Reproduction steps

1. insert SD prompt reader node
2. include image
3. queue prompt
4. error

### Image file

![654987](https://github.com/receyuki/comfyui-prompt-reader-node/assets/136205220/d975f3b7-2ec2-4a6a-85c0-23e2aefa6f68)

**Comment by receyuki** [comment]
The image you uploaded doesn't contain any metadata. It may have been compressed.

**Comment by MokkaBoss1** [comment]
[sd prompt reader (1).json](https://github.com/receyuki/comfyui-prompt-reader-node/files/14271144/sd.prompt.reader.1.json)

![Untitled](https://github.com/receyuki/comfyui-prompt-reader-node/assets/136205220/84a32dc6-66ef-4e67-becd-06ccdbf20933)

hope this works now - I just included the .json file and the image as an example

**Comment by receyuki** [comment]
I'm sorry to tell you that your photo still doesn't contain any metadata. It seems to have been edited with Affinity Photo, which may be the reason.

**Comment by MokkaBoss1** [comment]
Hi, yes that is the point

The node works fine where there is meta data. It is just the error handling
when there is no metadata. Ideally the workflow shouldn’t crash if there is
no metada.

Kind regards

Mokkaboss1

**Comment by MokkaBoss1** [comment]
Thank you. Just thought to let you know.

I'll close the issue
