### ISSUE TITLE
[BUG] - SD prompt saver node freezes workflow when name includes %model 

### ISSUE THREAD

**Issue by PhoenixFanta** [receyuki/comfyui-prompt-reader-node#61]
### Description

When filename includes %model with another placeholder , the node freezes, and I have to restart ComfyUI. There is no error message, it just gets stuck processing something in the SD prompt saver node. 

i.e
inputting "ComfyUI_%model_%counter" in the filename of the saver node freezes ComfyUI when it gets to the saver node

**Comment by receyuki** [comment]
Bug confirmed and will be fixed in the next version :)

**Comment by receyuki** [comment]
Please try the latest version.

**Comment by PhoenixFanta** [comment]
Works great now. Thanks for the quick fix !
