### ISSUE TITLE
[BUG] - Failed to install

### ISSUE THREAD

**Issue by lIlIlI11111111** [receyuki/comfyui-prompt-reader-node#69]
### Description

I tried to install via the ComfyUI manager, and while the terminal said that it worked, it showed up as (IMPORT FAILED) in the manager. I have also tried installing it manually, as well as deleting and reinstalling my venv, and neither of these approaches worked. I assumed that perhaps the manager was just mistaken, but when I tried to add a prompt reader node, there was no such node in any dialogue box. Here is the output text in the terminal after I tried installing with the manager:
```
Install custom node 'SD Prompt Reader'
Install: ['https://github.com/receyuki/comfyui-prompt-reader-node']
Download: git clone 'https://github.com/receyuki/comfyui-prompt-reader-node'
100%|██████████████████████████████████| 1154.0/1154.0 [00:04<00:00, 250.04it/s]
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/media/myUsername/26aaaf3e-1911-426f-b540-8c9564bf3d/8_AI/StableDiffThings/ComfyUI/venv/bin/python', '-m', 'pip', 'install', 'piexif']
 [!] WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
[!] You should consider upgrading via the '/media/myUsername/26aaaf3e-1911-426f-b540-8c9564bf3d/8_AI/StableDiffThings/ComfyUI/venv/bin/python -m pip install --upgrade pip' command.
Installation was successful.
After restarting ComfyUI, please refresh the browser.
FETCH DATA from: /media/myUsername/26aaaf3e-1911-426f-b540-8c9564bf3d/8_AI/StableDiffThings/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json
FETCH DATA from: /media/myUsername/26aaaf3e-1911-426f-b540-8c9564bf3d/8_AI/StableDiffThings/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json
```

### Reproduction steps

1) Be on Linux Mint
2) Install ComfyUI
3) Install Comfy manager
4) Search for "Prompt reader"
5) Click install
6) Error

### Image file

![image](https://github.com/receyuki/comfyui-prompt-reader-node/assets/115831873/18e5bcf0-a035-44cb-95ff-d43eb657eda3)

**Comment by receyuki** [comment]
This is weird, I've never seen anything like this before. 
When you launch ComfyUI through your terminal, if a custom node fails to import, it should display the corresponding reason for the error. Can you find the content related to comfyui-prompt-reader-node in the terminal's log and post it here?

**Comment by lIlIlI11111111** [comment]
Oh thanks. Yep, that fixed it.
