### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by xthedarknight99x** [receyuki/comfyui-prompt-reader-node#74]
### Description

Tried to install Comfyui-promp-reader-node by Comfyui manager and manually both failed.

  File "K:\ComfyUI\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node\nodes.py", line 31, in <module>
    from .stable_diffusion_prompt_reader.sd_prompt_reader.constants import (
ModuleNotFoundError: No module named 'comfyui-prompt-reader-node.stable_diffusion_prompt_reader.sd_prompt_reader'

Cannot import K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node module for custom nodes: No module named 'comfyui-prompt-reader-node.stable_diffusion_prompt_reader.sd_prompt_reader'

I followed this installation guide [installation guide](https://github.com/receyuki/comfyui-prompt-reader-node#installation)  as well as updated my main Python folder to 3.11.8

### Reproduction steps

1. Go to comfyui manager.
2. Install-Comfyui prompt-reader-node
3. run command prompt from the comfyui-prompt-reader-node folder.
4.  Run pip install -r requirements.txt
5. . Run git pull --recurse-submodules
6. Restart Comfyui

**Comment by kjames2001** [comment]
same problem here.

**Comment by receyuki** [comment]
@xthedarknight99x @kjames2001 
Usually, you don't need to do anything except "click install and restart comfyui in the comfyui manager".
But in this case, please delete the stable_diffusion_prompt_reader folder (if it exists) and run `git submodule update` inside the comfyui-prompt-reader-node folder to fix it.

**Comment by xthedarknight99x** [comment]
> @xthedarknight99x @kjames2001 Usually, you don't need to do anything except "click install and restart comfyui in the comfyui manager". But in this case, please delete the stable_diffusion_prompt_reader folder (if it exists) and run `git submodule update` inside the comfyui-prompt-reader-node folder to fix it.

Unfortunately that failed to work. The error I get when doing the git submodule update is 

K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node>git submodule update
      0 [main] sh 515 dofork: child -1 - forked process 36088 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1072586 [main] sh 515 dofork: child -1 - forked process 6084 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh 517 child_copy: dll data read copy failed, 0x1515000..0x1522010, done 0, windows pid 5960, Win32 error 299
3174859 [main] sh 515 dofork: child -1 - forked process 5960 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
7233837 [main] sh 515 dofork: child -1 - forked process 38916 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
15316357 [main] sh 515 dofork: child -1 - forked process 40904 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable

K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node>

Im not sure why its showing it died.

**Comment by receyuki** [comment]
> > @xthedarknight99x @kjames2001 Usually, you don't need to do anything except "click install and restart comfyui in the comfyui manager". But in this case, please delete the stable_diffusion_prompt_reader folder (if it exists) and run `git submodule update` inside the comfyui-prompt-reader-node folder to fix it.
> 
> Unfortunately that failed to work. The error I get when doing the git submodule update is
> 
> K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node>git submodule update 0 [main] sh 515 dofork: child -1 - forked process 36088 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 1072586 [main] sh 515 dofork: child -1 - forked process 6084 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 0 [main] sh 517 child_copy: dll data read copy failed, 0x1515000..0x1522010, done 0, windows pid 5960, Win32 error 299 3174859 [main] sh 515 dofork: child -1 - forked process 5960 died unexpectedly, retry 0, exit code 0xC0000005, errno 11 C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 7233837 [main] sh 515 dofork: child -1 - forked process 38916 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 15316357 [main] sh 515 dofork: child -1 - forked process 40904 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable
> 
> K:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node>
> 
> Im not sure why its showing it died.

It looks like there's something wrong with your Git. I'm not really sure what's going on either.

**Comment by xthedarknight99x** [comment]
I am happy to report that disabling Mandatory ALSR fixes the issue.  See the post below for more details. https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors

**Comment by xthedarknight99x** [comment]
Install no longer fails.
