### ISSUE TITLE
[FEATURE REQUEST] - Positive and Negative Aesthetic Score print from Parameters output in Parameter Generator node

### ISSUE THREAD

**Issue by alessandroperilli** [receyuki/comfyui-prompt-reader-node#8]
### Summary

Currently, the SD Parameter Generator node allows the definition of both the Positive and Negative Aesthetic Score values, particularly important for SDXL Refiner. However, these two values are not printed as part of the Parameters output generated by the node.

<img width="470" alt="Screenshot 2023-10-26 at 09 39 35" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/9775949/95969130-2330-46d7-96ca-c53e20b78e6c">

Would it be possible to add them to the output (perhaps, between the Scheduler and the Size outputs)?

### Basic Example

Positive aesthetic score: 6.00
Negative aesthetic score: 2.50

**Comment by receyuki** [comment]
I remember we may have discussed this before where I thought showing these SDXL parameters to non-SDXL users could be somewhat strange. How about I use the model_version to determine whether to display them?

**Comment by alessandroperilli** [comment]
Sure. That works just fine.

**Comment by alessandroperilli** [comment]
The new version of the node is fantastic. Thank you.
