### ISSUE TITLE
[BUG] - SD Prompt Saver - Time format filename issue

### ISSUE THREAD

**Issue by Davikar** [receyuki/comfyui-prompt-reader-node#80]
### Description

If I want to use a . as a separator in the timeformat in the SD Prompt Saver, the last part gets cut off.
For example %H.%M.%S produces 21.11 instead of 21.11.59.
Also, I have to queue twice to get the new values in the file name.

### Reproduction steps

1. Load SD Prompt Saver
2. Type %H.%M.%S in time_format field
3. Queue twice

**Comment by jinxishe** [comment]
It's not just time format, anything, like cfg 3.5 will cause filename cut. seems the '.' causes problem.

**Comment by Davikar** [comment]
Thanks! 👍
