### ISSUE TITLE
[BUG] - the scheduler from SD Parameter Generator cannot connect to Ksampler or any other node which has scheduler as an input

### ISSUE THREAD

**Issue by jinxishe** [receyuki/comfyui-prompt-reader-node#81]
### Description

the scheduler from SD Parameter Generator cannot connect to Ksampler or any other node which has scheduler as an input.
It seems happen with recent ComfyUI Update.

### Image file

![scheduler](https://github.com/receyuki/comfyui-prompt-reader-node/assets/25061293/b3e73f3d-a8d4-4964-a066-8d39f9eb10be)

**Comment by receyuki** [comment]
Everything is working fine on my end. I also checked the latest updates for ComfyUI, and it doesn't seem like there are any commits related to KSampler. My suggestion is to restart the ComfyUI, refresh the webpage, and delete and re-add both nodes.
<img width="568" alt="截屏2024-06-30 上午1 49 12" src="https://github.com/receyuki/comfyui-prompt-reader-node/assets/28808141/03c4765e-9b97-4337-b825-8a9814a48315">

**Comment by robertwaleda** [comment]
Unfortunately I have the same issue. Sometimes the connection between SD Parameter generator and a KSampler is not possible. But then with another tryout, it is connected. Then when running a queue, no scheduler input at Sampler (red circle). I have found that the scheduler output of the SD Parameter Generator is not present. If I change the scheduler input  widget from KSampler back, and choose a scheduler name, then Sampler is working fine.  So my first impression is that this is a bug within SD Parameter Generator, using the most recent updated ComfyUI. I have already re-added the node, but problem still exists. For the record, I have a Mac Studio M2 Max.

**Comment by jinxishe** [comment]
I forgot where I saw it, but it seems that a recent update to ComfyUI made adjustments to scheduler-related functions. All custom nodes involving the scheduler might need some modifications. However, I can't remember the specific details, so I apologize for that.

> Everything is working fine on my end. I also checked the latest updates for ComfyUI, and it doesn't seem like there are any commits related to KSampler. My suggestion is to restart the ComfyUI, refresh the webpage, and delete and re-add both nodes. <img alt="截屏2024-06-30 上午1 49 12" width="568" src="https://private-user-images.githubusercontent.com/28808141/344422335-03c4765e-9b97-4337-b825-8a9814a48315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTAyMTQsIm5iZiI6MTcxOTg4OTkxNCwicGF0aCI6Ii8yODgwODE0MS8zNDQ0MjIzMzUtMDNjNDc2NWUtOWI5Ny00MzM3LWI4MjUtOGE5ODE0YTQ4MzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZWNmY2IyODExMmYxMTczNWY5MWU4ZTBlNTcwOTVmMTE0ZmY3MWU2ZTVlY2M0ZTQwY2E3YjhlYTc2OTkzZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_OE4xyQz7p-V32PyC5JlvfwJRFTkT-xl6fxjc2LfNk">

**Comment by jinxishe** [comment]
> @robertwaleda @jinxishe Have any other custom nodes had similar issues recently? I can’t figure out what the problem is.

yes. other custom nodes like Impact Scheduler Adapter(from Impact Pack) and XY Input:Sampler/Scheduler(from Efficiency Node) have same problems. 


![3207ece2-2a66-4e14-a86c-e11f7250ce34](https://github.com/receyuki/comfyui-prompt-reader-node/assets/25061293/28705e7b-7a6f-43d3-9eb3-2347a999d4c2)

**Comment by receyuki** [comment]
> > @robertwaleda @jinxishe Have any other custom nodes had similar issues recently? I can’t figure out what the problem is.
> 
> yes. other custom nodes like Impact Scheduler Adapter(from Impact Pack) and XY Input:Sampler/Scheduler(from Efficiency Node) have same problems.
> 
> ![3207ece2-2a66-4e14-a86c-e11f7250ce34](https://private-user-images.githubusercontent.com/25061293/345480739-28705e7b-7a6f-43d3-9eb3-2347a999d4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjEwNTgsIm5iZiI6MTcyMDAyMDc1OCwicGF0aCI6Ii8yNTA2MTI5My8zNDU0ODA3MzktMjg3MDVlN2ItN2E2Zi00M2QzLTllYjMtMjM0N2E5OTlkNGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE1MzIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjFiZmVjMGQ4ZWQ5ZDgwYmNjMWViYWM0YzU2YjQ4MDkwYjZkMjNjN2RlNWI1ZGJjODQ1ZDVjNGZjNmFlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFtGxvn6X9p6lEOo0im6IAND0ndvayCTF-FR5yLI1BQ)

If the authors of these nodes can figure out the problem and solution, I should be able to use it as a reference.

**Comment by jinxishe** [comment]
> > > @robertwaleda @jinxishe Have any other custom nodes had similar issues recently? I can’t figure out what the problem is.
> > 
> > 
> > yes. other custom nodes like Impact Scheduler Adapter(from Impact Pack) and XY Input:Sampler/Scheduler(from Efficiency Node) have same problems.
> > ![3207ece2-2a66-4e14-a86c-e11f7250ce34](https://private-user-images.githubusercontent.com/25061293/345480739-28705e7b-7a6f-43d3-9eb3-2347a999d4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjEwNTgsIm5iZiI6MTcyMDAyMDc1OCwicGF0aCI6Ii8yNTA2MTI5My8zNDU0ODA3MzktMjg3MDVlN2ItN2E2Zi00M2QzLTllYjMtMjM0N2E5OTlkNGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE1MzIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjFiZmVjMGQ4ZWQ5ZDgwYmNjMWViYWM0YzU2YjQ4MDkwYjZkMjNjN2RlNWI1ZGJjODQ1ZDVjNGZjNmFlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFtGxvn6X9p6lEOo0im6IAND0ndvayCTF-FR5yLI1BQ)
> 
> If the authors of these nodes can figure out the problem and solution, I should be able to use it as a reference.

I got some interesting result. When I disabled the Efficiency Node, the problem disappeared. Seems like the AYS-xxxx schedulers added by Efficiency Node caused the problem. I will check the Efficiency Node's issues. Thanks a lot!

**Comment by jinxishe** [comment]
I confirmed it's the Efficiency Node's bug. And it's been fixed recently.(https://github.com/jags111/efficiency-nodes-comfyui/pull/210) After update to newest code, everything is OK now. 
Thanks again. I'll close this issue.

**Comment by receyuki** [comment]
Looks like my version of Efficiency Node is too old, which is why this bug didn't appear.

**Comment by robertwaleda** [comment]
Just tested the scheduler connection between SD Parameter Generator and the KSampler from Efficiency Nodes. The issue is still present. As a temporary workaround, I now use the native scheduler from the KSampler node, as this is also advised by the maintainer ( see https://github.com/jags111/efficiency-nodes-comfyui/issues/208 ). So I think that this case can be closed, because in fact it has to be addressed as an issue with Efficiency Nodes. Thanks for your help.

**Comment by robertwaleda** [comment]
Extra info: The last update of the Efficiency nodes on my Mac has been done on June 24th. So I suppose that the 210 patch is included.
