### ISSUE TITLE
[BUG] - When using the latest code of ComfyUI, the SD Parameter Extractor node reports an error.

### ISSUE THREAD

**Issue by jinxishe** [receyuki/comfyui-prompt-reader-node#90]
### Description

![1](https://github.com/user-attachments/assets/8ef43910-b3ad-42b3-acab-95134f6eb46f)
![2](https://github.com/user-attachments/assets/cccaeefc-8131-452d-a506-94189d0f1150)

**Comment by UntrustWasTaken** [comment]
Same issue. If you reset the extractor node so the parameter is just "parameters not loaded", queue the prompt, it will be populated with first value (in my case, "steps"), queue again and this error happens. frustrating.

**Comment by receyuki** [comment]
@jinxishe @UntrustWasTaken 
I've fixed the issue in the latest version. Please try the new version.

**Comment by jinxishe** [comment]
> @jinxishe @UntrustWasTaken I've fixed the issue in the latest version. Please try the new version.

solved! thanks a lot!
